### ISSUE TITLE
Flexibility with breakpoints

### ISSUE THREAD

**Issue by oyeanuj** [kristof0425/react-with-breakpoints#27]
Hi @kristof0425, thank you for putting out this library! The design looks great, but I noticed that one can only specify three breakpoints: small, medium and large. I'm wondering your thoughts on making that object more flexible or allow overriding it from the props in `ShowAt` and `HideAt`?

In our app, we have a few more breakpoints for more granular behavior, as well as some custom breakpoints for certain pages and layouts. And I am not sure how to implement those with this library.

Thoughts?

**Comment by kristof0425** [comment]
Hello @oyeanuj 👋,

Sorry for replying so late! First of all, thank you for considering using `react-with-breakpoints`!

My main goal with `react-with-breakpoints` has always been one thing: open-sourcing Airbnb's responsive utility components, which were introduced in [this article](https://medium.com/airbnb-engineering/rearchitecting-airbnbs-frontend-5e213efc24d2). Therefore I always tried to make them work like those components.

Now you know what my goal is with this project, I'm going to answer your question. Let me decompose it into two parts:

#### 1. Passing custom breakpoints object through `ShowAt` and `HideAt`.

With the version 3 of `react-with-breakpoints`, I introduced a new API, which leverages the React 16.3 Context API. This way I could centralize the override of the breakpoints objects (meaning you can only pass it to `BreakpointsProvider` from now on). This has always been my goal since `v1`, but I only managed to solve it with this release. 
So I regret to tell you, but I'm not planning to add the ability to `ShowAt` and `HideAt` to be able to get custom breakpoints via props. 😔

#### 2. Allowing more flexible breakpoints objects

As I mentioned, these components tried to be a copy of Airbnb's responsive utility components so they would function the same way. Those components define 3 breakpoints `small`, `medium`, `large`. 
Although my components are just as limited as Aribnb's, I took a look at my code, how I could support more flexible breakpoints objects.

The problem is only at the `setShouldrender` function:
https://github.com/kristof0425/react-with-breakpoints/blob/a4bd4836530c759e983a789b096329f71c1d10bd/src/ShowAt.js#L9-L19

This is where the logic is created so to say, whether the component should return its children or not. IMHO if you provided your custom flexible breakpoints you would also need to provide "your logic" with it.
My goal with this component was to make leaner webpages really easy and it should hide complexity, therefore I wouldn't add the ability to the users that they could provide their own logic.

I hope my answer is satisfactory enough for you!

Despite all of this, I'm open for ideas how we could still support your requests and keep the functioning like the Airbnb modules have in the same time.
